### ISSUE TITLE
数据集问题

### ISSUE THREAD

**Issue by AnubisYe** [RogerMonkey/justtest#1]
user_pay user_view的数据集您还有吗。。。现在大赛结束了数据集没地下载

**Comment by RogerMonkey** [comment]
点错了，我帮你找找

**Comment by RogerMonkey** [comment]
没找到，非常抱歉。

**Comment by DrJZhou** [comment]
我有，发你邮箱csyezy@163.com
  @AnubisYe

**Comment by AnubisYe** [comment]
好的谢谢




-------- 原始邮件 --------
发件人：周杰 <notifications@github.com>
时间：周五 1月5日 12:20
收件人：RogerMonkey/IJCAI_CUP_2017 <IJCAI_CUP_2017@noreply.github.com>
抄送："Zy.Yip" <csyezy@163.com>,Author <author@noreply.github.com>
主题：Re: [RogerMonkey/IJCAI_CUP_2017] 数据集问题 (#1)
